function f=sk(u,g)
global ipx imx ipy imy h;
f=((u(ipx,:,1)+u(:,:,1)).*g(ipx,:)...
  -(u(imx,:,1)+u(:,:,1)).*g(imx,:)...
  +(u(:,ipy,2)+u(:,:,2)).*g(:,ipy)...
  -(u(:,imy,2)+u(:,:,2)).*g(:,imy))/(4*h);
